#!/usr/bin/env bash
# SharX interactive installer — provisions .env, builds the docker stack, brings it up.
# Idempotent: re-runs preserve existing values unless the user clears them.
#
# Usage:
#   sudo bash scripts/install-sharx.sh
#
# What it does:
#   1. Asks for PANEL_DOMAIN (or empty for IP-mode + self-signed TLS).
#   2. Asks for PANEL_DECOY_URL (https URL of a real third-party site to mirror).
#   3. Generates PANEL_SECRET_PREFIX + WATCHTOWER_HTTP_API_TOKEN if missing.
#   4. Writes .env (chmod 600, gitignored).
#   5. docker compose build && docker compose up -d.
#   6. Prints the panel URL.
#
# Re-run with `--rotate-prefix` to spin a fresh secret prefix without touching anything else.

set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE=".env"

# ---- helpers ----
log()  { printf '\033[1;36m[install]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[fail]\033[0m %s\n' "$*" >&2; exit 1; }

# Read existing .env value (empty if missing).
get_env() {
    local key="$1"
    [ -f "$ENV_FILE" ] || { echo ""; return; }
    grep -E "^${key}=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2- || echo ""
}

# Prompt the user with a default; returns input (or default if blank).
prompt() {
    local question="$1" default="$2" answer
    if [ -n "$default" ]; then
        read -r -p "$question [$default]: " answer
        echo "${answer:-$default}"
    else
        read -r -p "$question: " answer
        echo "$answer"
    fi
}

# ---- preflight ----
command -v docker >/dev/null || fail "docker not found. Install Docker first."
docker compose version >/dev/null 2>&1 || fail "docker compose plugin not found. Install with apt-get install docker-compose-plugin."

# ---- rotate-prefix shortcut ----
if [ "${1:-}" = "--rotate-prefix" ]; then
    [ -f "$ENV_FILE" ] || fail "$ENV_FILE missing — run installer first."
    new_prefix="$(openssl rand -hex 8)"
    sed -i.bak "s|^PANEL_SECRET_PREFIX=.*|PANEL_SECRET_PREFIX=${new_prefix}|" "$ENV_FILE"
    rm -f "${ENV_FILE}.bak"
    log "Rotated PANEL_SECRET_PREFIX → ${new_prefix}"
    log "Restart Caddy to apply: docker compose restart caddy"
    exit 0
fi

# ---- collect values ----
log "Configuring SharX. Existing values from .env are kept unless you change them."

current_domain="$(get_env PANEL_DOMAIN)"
echo
echo "PANEL_DOMAIN — public hostname pointing to this server (DNS A/AAAA must exist)."
echo "  Leave EMPTY to use the server's IP with self-signed TLS (browsers will warn)."
PANEL_DOMAIN="$(prompt 'PANEL_DOMAIN' "$current_domain")"

current_decoy="$(get_env PANEL_DECOY_URL)"
[ -z "$current_decoy" ] && current_decoy="https://news.ycombinator.com"
echo
echo "PANEL_DECOY_URL — https:// URL Caddy mirrors for all unrecognized paths (Hiddify decoy pattern)."
echo "  Pick a plausible third-party site; scanners will see its content instead of SharX."
PANEL_DECOY_URL="$(prompt 'PANEL_DECOY_URL' "$current_decoy")"

if [[ ! "$PANEL_DECOY_URL" =~ ^https:// ]]; then
    fail "PANEL_DECOY_URL must start with https:// (got: $PANEL_DECOY_URL)"
fi

PANEL_SECRET_PREFIX="$(get_env PANEL_SECRET_PREFIX)"
if [ -z "$PANEL_SECRET_PREFIX" ]; then
    PANEL_SECRET_PREFIX="$(openssl rand -hex 8)"
    log "Generated PANEL_SECRET_PREFIX = $PANEL_SECRET_PREFIX"
fi

WATCHTOWER_HTTP_API_TOKEN="$(get_env WATCHTOWER_HTTP_API_TOKEN)"
if [ -z "$WATCHTOWER_HTTP_API_TOKEN" ]; then
    WATCHTOWER_HTTP_API_TOKEN="$(openssl rand -hex 24)"
    log "Generated WATCHTOWER_HTTP_API_TOKEN"
fi

# ---- write .env ----
umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/install-sharx.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ").
# DO NOT COMMIT — .env is gitignored.

PANEL_DOMAIN=${PANEL_DOMAIN}
PANEL_SECRET_PREFIX=${PANEL_SECRET_PREFIX}
PANEL_DECOY_URL=${PANEL_DECOY_URL}
WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
EOF
chmod 600 "$ENV_FILE"
log "Wrote $ENV_FILE (chmod 600)"

# ---- build + up ----
log "Building images (panel + caddy). This can take 5-15 minutes on a 1 GB VPS."
docker compose build

log "Starting stack..."
docker compose up -d

# ---- final report ----
echo
log "SharX stack started."
if [ -n "$PANEL_DOMAIN" ]; then
    log "Panel  → https://${PANEL_DOMAIN}/${PANEL_SECRET_PREFIX}/"
    log "Sub    → https://${PANEL_DOMAIN}/${PANEL_SECRET_PREFIX}-sub/"
else
    log "Panel  → https://<server-ip>/${PANEL_SECRET_PREFIX}/   (self-signed TLS warning expected)"
fi
log "Decoy  → all other paths transparently mirror ${PANEL_DECOY_URL}"
log "Mascaraed mode activates 1 hour after first boot (root '/' also routes to decoy)."
echo
log "View logs: docker compose logs -f caddy sharx"
log "Rotate prefix: bash scripts/install-sharx.sh --rotate-prefix"
